### ISSUE TITLE
Standardize Function Syntax to ES6 Format

### ISSUE THREAD

**Issue by petermsouzajr** [petermsouzajr/cy-shadow-report#29]
### Issue Overview
We have identified that most of our codebase utilizes ES6 syntax. However, there is at least one function still written in the older CommonJS format. This inconsistency can lead to potential confusion and maintenance challenges.

### Expected Outcome
- Ensure that all functions within our codebase conform to the ES6 syntax standard.
- This will bring uniformity to our code and may improve readability and future maintainability.

### Specifics
- Locate the function(s) using the older CommonJS format.
- Refactor these functions to the ES6 standard, ensuring that functionality remains unaffected.
- Test thoroughly to ensure that refactoring does not introduce any regressions.

### Contribution Guidelines
- Please reference this issue in your pull request.
- Ensure that your code follows our existing style guidelines.
- Add comments where necessary to clarify complex logic after refactoring.
- If multiple functions need refactoring, consider submitting separate pull requests for each to simplify review.

We welcome contributions to this issue and appreciate your help in improving the consistency and quality of our project's codebase.

**Comment by Lukada-taiya** [comment]
Please assign me this issue. I am happy to help.

**Comment by petermsouzajr** [comment]
thanks! you can comment -  -Dot Take-  on any issue to claim it, and it will be assigned to you, taken from the CONTRIBUTING doc, Claiming an Issue section. 
<img width="251" alt="Screenshot 2024-01-11 at 11 45 29 AM" src="https://github.com/petermsouzajr/cy-shadow-report/assets/13664490/01f1b6af-14f1-44e3-b272-6e87cccc2139">
