### ISSUE TITLE
Feature: Add issue templates

### ISSUE THREAD

**Issue by adiati98** [petermsouzajr/cy-shadow-report#38]
## Description

There are sections about how to write an issue for Reporting Bugs and Suggesting Enhancements in the [How Can I Contribute?](https://github.com/petermsouzajr/cy-shadow-report/blob/main/CONTRIBUTING.md#how-can-i-contribute) section on the Contributing Guidelines. And these contain clear instructions about how to write issues.

However, there would still be a chance where contributors miss to include important information that maintainers need.

## Suggested solution

- Create issue templates for reporting bugs and suggesting enhancements. It will give these benefits:

    - Prevent contributors to miss giving all information needed.
    - Make it easier for maintainers to triage and prioritize the issues.

- If issue templates are provided, it is safe to remove "Reporting Bugs" and "Suggesting Enhancements" sections completely from the COntributing Guide. This can reduce the length of the guide.

**Comment by adiati98** [comment]
Hey @petermsouzajr it would be an honor if I can contribute to this one, if you agree with the proposal! 😊

**Comment by petermsouzajr** [comment]
@adiati98  That sounds like a great improvement, thanks! Would you like to create a PR to remove the  "Reporting Bugs" and "Suggesting Enhancements" sections from the `CONTRIBUTING` doc?

**Comment by adiati98** [comment]
@petermsouzajr absolutely!

Just to confirm, do you want me to only remove them from `CONTRIBUTING.md` or also create the templates?

**Comment by petermsouzajr** [comment]
@adiati98  Yes, please also create the templates. 💪

**Comment by adiati98** [comment]
@petermsouzajr will do!
Can you please assign the issue to me to prevent others spend their times to work on the issue?

Thanks!
